app/blog/urls.py
from django.urls import path
from . import views


app_name = "blog"


urlpatterns = [
    # Other URL patterns
    path('blogs/', views.blog_post_list, name='blog_post_list'),
    path('blog/<str:title>/', views.blog_post_detail, name='blog_post_detail'),
]

app/core/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("service.urls")),
    path("", include("blog.urls")),
    path("api/", include("service_api.urls")),
    path("accounts/", include("allauth.urls")),
    path('paypal/', include('paypal.standard.ipn.urls')),
    re_path('djga/', include('google_analytics.urls')),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/blog/models.py
from django.db import models


class BlogPost(models.Model):
    title = models.CharField(max_length=255, unique=True)
    content = models.TextField()
    publish_date = models.DateTimeField(auto_now_add=True)
    meta_description = models.TextField(null=True, blank=True)
    keywords = models.TextField(max_length=255)
    # Add this field for the image
    image = models.ImageField(upload_to='blog_images/')
    # Add other fields as needed

    def __str__(self):
        return self.title

app/blog/forms.py
from django import forms
from .models import BlogPost

class BlogPostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ('title', 'content', 'keywords', 'meta_description', 'image')  # Add 'image' field

app/blog/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, get_object_or_404
from .models import BlogPost

def blog_post_detail(request, title):
    blog_post = get_object_or_404(BlogPost, title=title)
    return render(request, 'blog/blog_post_detail.html', {'blog_post': blog_post})


def blog_post_list(request):
    blog_posts = BlogPost.objects.all()
    return render(request, 'blog/blog_post_list.html', {'blog_posts': blog_posts})

app/templates/blog/blog_post_detail.html
{% extends "base.html" %}

{% block head %}
    <title>{% block title %}{{ blog_post.title }}{% endblock %}</title>
    <meta name="title" content="{{ blog_post.title }}">
    <meta name="description" content="{{ blog_post.meta_description }}">
    <meta name="keywords" content="{{ blog_post.keywords }}">
{% endblock %}

{% block content %}
    {% load static %}
    {% load crispy_forms_tags %}

    <section id="hero" class="clearfix">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    <div class="card shadow">
                        <img src="{{ blog_post.image.url }}" alt="{{ blog_post.title }}" class="card-img-top">
                        <div class="card-body">
                            <h2 class="card-title">{{ blog_post.title }}</h2>
                            <p class="card-text">{{ blog_post.content }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

app/templates/blog/blog_post_list.html
{% extends "base.html" %}

{% block head %}
    <title>{% block title %}Blogs{% endblock %}</title>
    <meta name="title" content="Florida Roof Marketplace Blog">
    <meta name="description" content="Blogs">
    <meta name="keywords" content="Blogs">
{% endblock %}

{% block content %}
    {% load static %}
    {% load crispy_forms_tags %}

    <section id="hero" class="clearfix">
        <div class="container">
            <div class="row justify-content-center">
                <!-- Loop through blog posts -->
                {% for post in blog_posts %}
                    <div class="col-md-6 col-lg-4 mb-4">
                        <div class="card shadow">
                            <div class="card-img-container">
                                <img src="{{ post.image.url }}" alt="{{ post.title }}" class="card-img">
                            </div>
                            <div class="card-body">
                                <h2 class="card-title"><a href="{% url 'blog:blog_post_detail' title=post.title %}">{{ post.title }}</a></h2>
                                <p class="card-text">{{ post.short_content|truncatewords:20 }}</p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>

    <style>
        .card-img-container {
            width: 100%;
            height: 200px; /* Set the desired fixed height */
            overflow: hidden;
        }
        .card-img {
            width: 100%;
            height: auto;
            object-fit: cover; /* Crop the image to fit the container */
            vertical-align: middle;
        }
    </style>
{% endblock %}